 object oriented programming, design and development of Multi - Tier distributed, Enterprise applications using Java and J2EE technologies with Software Development Life Cycle
  writing SQL queries with major Relational Databases
  Used LOG4J & JUnit for debugging, testing and maintaining the system state
  Built RESTful Webservices interface implemented in Java.
  Involved in the development of presentation layer and GUI framework in JSP, HTML and client side validations were done using JavaScript.
  Participated in Agile Scrums and Sprints.